// src/data/products.js
export const productsData = [
  { 
    id: 1, 
    name: "Potato 500g", 
    category: "Vegetables", 
    price: 40, 
    offerPrice: 30, 
    rating: 4, 
    image: '/potato_image_1.png',
    images: ['/potato_image_1.png','/potato_image_2.png','/potato_image_3.png','/potato_image_4.png'],
    description: ["Fresh farm potatoes", "Rich in carbohydrates", "Perfect for boiling or frying"]
  },
  { 
    id: 2, 
    name: "Tomato 1kg", 
    category: "Vegetables", 
    price: 50, 
    offerPrice: 40, 
    rating: 4, 
    image: '/tomato_image.png',
    images: ['/tomato_image.png','/tomato_image_2.png'],
    description: ["Organic red tomatoes", "High in Vitamin C", "Best for salads and curries"]
  },
  { 
    id: 3, 
    name: "Carrot 500g", 
    category: "Vegetables", 
    price: 60, 
    offerPrice: 50, 
    rating: 4, 
    image: '/carrot_image.png',
    images: ['/carrot_image.png'],
    description: ["Sweet and crunchy", "Good for eyesight", "Grown without pesticides"]
  },
  { 
    id: 4, 
    name: "Spinach 500g", 
    category: "Vegetables", 
    price: 25, 
    offerPrice: 20, 
    rating: 4, 
    image: '/spinach_image_1.png',
    images: ['/spinach_image_1.png'],
    description: ["Iron-rich leafy green", "Freshly picked daily", "Wash before use"]
  },
  { 
    id: 5, 
    name: "Onion 500g", 
    category: "Vegetables", 
    price: 40, 
    offerPrice: 30, 
    rating: 4, 
    image: '/onion_image_1.png',
    images: ['/onion_image_1.png'],
    description: ["Pungent and flavorful", "Essential for Indian cooking", "Store in a cool dry place"]
  },
  { 
    id: 6, 
    name: "Apple 1kg", 
    category: "Fruits", 
    price: 150, 
    offerPrice: 120, 
    rating: 4, 
    image: '/apple_image.png',
    images: ['/apple_image.png'],
    description: ["Crisp and juicy", "Sweet taste", "Keep refrigerated for freshness"]
  },
  { 
    id: 7, 
    name: "Amul Milk 1L", 
    category: "Dairy", 
    price: 85, 
    offerPrice: 80, 
    rating: 4, 
    image: '/amul_milk_image.png',
    images: ['/amul_milk_image.png'],
    description: ["Pasteurized toned milk", "Rich in calcium", "Ready to drink or boil"]
  },
  { 
    id: 8, 
    name: "Coca Cola 1.5L", 
    category: "Drinks", 
    price: 90, 
    offerPrice: 70, 
    rating: 4, 
    image: '/coca_cola_image.png',
    images: ['/coca_cola_image.png'],
    description: ["Classic carbonated drink", "Best served chilled", "Contains caffeine"]
  },
  { 
    id: 9, 
    name: "Basmati Rice 5kg", 
    category: "Grains", 
    price: 750, 
    offerPrice: 670, 
    rating: 4, 
    image: '/basmati_rice_image.png',
    images: ['/basmati_rice_image.png'],
    description: ["Long grain aromatic rice", "Aged for better taste", "Ideal for Biryani and Pulao"]
  },
  { 
    id: 10, 
    name: "Brown Bread", 
    category: "Bakery", 
    price: 60, 
    offerPrice: 50, 
    rating: 4, 
    image: '/brown_bread_image.png',
    images: ['/brown_bread_image.png'],
    description: ["Whole wheat flour", "Rich in fiber", "Freshly baked daily"]
  },
  { 
    id: 11, 
    name: "Yippee Maggi", 
    category: "Instant", 
    price: 25, 
    offerPrice: 20, 
    rating: 4, 
    image: '/maggi_image.png',
    images: ['/maggi_image.png'],
    description: ["Quick 2-minute snack", "Tasty masala included", "Non-sticky noodles"]
  },
  { 
    id: 12, 
    name: "Orange 1kg", 
    category: "Fruits", 
    price: 200, 
    offerPrice: 180, 
    rating: 4, 
    image: '/orange_image.png',
    images: ['/orange_image.png', ],
    description: ["Sweet and tangy", "Excellent source of Vitamin C", "Easy to peel"]
  },
  { 
    id: 13, 
    name: "Banana 1kg", 
    category: "Fruits", 
    price: 120, 
    offerPrice: 99, 
    rating: 4, 
    image: '/banana_image_1.png',
    images: ['/banana_image_1.png'],
    description: ["Natural energy booster", "Rich in potassium", "Ripened naturally"]
  },
  { 
    id: 14, 
    name: "Mango 1kg", 
    category: "Fruits", 
    price: 180, 
    offerPrice: 140, 
    rating: 4, 
    image: '/mango_image_1.png',
    images: ['/mango_image_1.png'],
    description: ["The king of fruits", "Sweet and pulpy", "Seasonal specialty"]
  },
  { 
    id: 15, 
    name: "Grapes 500g", 
    category: "Fruits", 
    price: 110, 
    offerPrice: 90, 
    rating: 4, 
    image: '/grapes_image_1.png',
    images: ['/grapes_image_1.png'],
    description: ["Seedless sweet grapes", "Wash thoroughly before eating", "Rich in antioxidants"]
  },
  { 
    id: 16, 
    name: "Paneer 200g", 
    category: "Dairy", 
    price: 130, 
    offerPrice: 110, 
    rating: 4, 
    image: '/paneer_image.png',
    images: ['/paneer_image.png'],
    description: ["Fresh malai paneer", "Soft and creamy texture", "High protein content"]
  },
  { 
    id: 17, 
    name: "Eggs 12pcs", 
    category: "Dairy", 
    price: 100, 
    offerPrice: 90, 
    rating: 4, 
    image: '/eggs_image.png',
    images: ['/eggs_image.png'],
    description: ["Farm fresh eggs", "Standard size", "Quality assured"]
  },
  { 
    id: 18, 
    name: "Cheese 200g", 
    category: "Dairy", 
    price: 150, 
    offerPrice: 120, 
    rating: 4, 
    image: '/cheese_image.png',
    images: ['/cheese_image.png'],
    description: ["Processed cheddar cheese", "Rich and creamy", "Perfect for sandwiches and pizza"]
  },
  { 
    id: 19, 
    name: "Sprite 1.5L", 
    category: "Drinks", 
    price: 80, 
    offerPrice: 60, 
    rating: 4, 
    image: '/sprite_image_1.png',
    images: ['/sprite_image_1.png'],
    description: ["Lemon-lime flavored soda", "Refreshing thirst quencher", "Zero caffeine"]
  },
  { 
    id: 20, 
    name: "7up 1.5L", 
    category: "Drinks", 
    price: 90, 
    offerPrice: 70, 
    rating: 4, 
    image: '/seven_up_image_1.png',
    images: ['/seven_up_image_1.png'],
    description: ["Natural lemon and lime flavor", "Clear carbonated beverage", "Crisp and clean taste"]
  },
  { 
    id: 21, 
    name: "Fanta 1.5L", 
    category: "Drinks", 
    price: 90, 
    offerPrice: 70, 
    rating: 4, 
    image: '/fanta_image_1.png',
    images: ['/fanta_image_1.png'],
    description: ["Bright orange flavor", "Bold and bubbly", "Great for parties"]
  },
  { 
    id: 22, 
    name: "Wheat Flour 5kg", 
    category: "Grains", 
    price: 420, 
    offerPrice: 380, 
    rating: 4, 
    image: '/wheat_flour_image.png',
    images: ['/wheat_flour_image.png'],
    description: ["100% whole wheat", "Stone-ground (Chakki Atta)", "Soft rotis every time"]
  },
  { 
    id: 23, 
    name: "Organic Oats", 
    category: "Grains", 
    price: 250, 
    offerPrice: 200, 
    rating: 4, 
    image: '/quinoa_image.png',
    images: ['/quinoa_image.png'],
    description: ["Rolled oats", "Heart-healthy breakfast", "Gluten-free option"]
  },
  { 
    id: 24, 
    name: "Brown Rice 1kg", 
    category: "Grains", 
    price: 260, 
    offerPrice: 220, 
    rating: 4, 
    image: '/brown_rice_image.png',
    images: ['/brown_rice_image.png'],
    description: ["Unpolished whole grain", "Low glycemic index", "High in minerals"]
  },
  { 
    id: 25, 
    name: "Barley 1kg", 
    category: "Grains", 
    price: 240, 
    offerPrice: 200, 
    rating: 4, 
    image: '/barley_image.png',
    images: ['/barley_image.png'],
    description: ["Hulled barley grains", "Great for soups and stews", "High in dietary fiber"]
  },
  { 
    id: 26, 
    name: "Butter Croissant 100g", 
    category: "Bakery", 
    price: 60, 
    offerPrice: 45, 
    rating: 4, 
    image: '/butter_croissant_image.png',
    images: ['/butter_croissant_image.png'],
    description: ["Flaky and buttery", "Authentic French style", "Best served warm"]
  },
  { 
    id: 27, 
    name: "Knorr Cup Soup", 
    category: "Instant", 
    price: 160, 
    offerPrice: 140, 
    rating: 4, 
    image: '/knorr_soup_image.png',
    images: ['/knorr_soup_image.png'],
    description: ["Rich tomato soup", "Instant preparation", "No added preservatives"]
  },
];